-- VXCHAT V1 database
-- Run this in Supabase SQL Editor.
-- IMPORTANT: this script assumes a fresh VXCHAT schema.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null,
  avatar_url text,
  bio text,
  last_seen timestamptz,
  created_at timestamptz not null default now(),
  constraint username_format check (username ~ '^[a-z0-9_]{3,24}$'),
  constraint display_name_length check (char_length(display_name) between 1 and 50)
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (conversation_id, user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  constraint message_length check (char_length(content) between 1 and 4000)
);

create index if not exists profiles_username_idx on public.profiles(username);
create index if not exists members_user_idx on public.conversation_members(user_id);
create index if not exists messages_conversation_idx on public.messages(conversation_id, created_at);

-- Create profile automatically after Auth signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  requested_username text;
  requested_display_name text;
begin
  requested_username := lower(coalesce(new.raw_user_meta_data->>'username', split_part(new.email, '@', 1)));
  requested_display_name := coalesce(nullif(new.raw_user_meta_data->>'display_name', ''), requested_username);

  insert into public.profiles (id, username, display_name)
  values (new.id, requested_username, requested_display_name);

  return new;
exception when unique_violation then
  raise exception 'Username is already taken';
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- RLS
alter table public.profiles enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;

drop policy if exists "profiles readable by authenticated users" on public.profiles;
create policy "profiles readable by authenticated users"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "members can read conversations" on public.conversations;
create policy "members can read conversations"
on public.conversations for select
to authenticated
using (
  exists (
    select 1 from public.conversation_members cm
    where cm.conversation_id = id and cm.user_id = auth.uid()
  )
);

drop policy if exists "members can read membership" on public.conversation_members;
create policy "members can read membership"
on public.conversation_members for select
to authenticated
using (
  user_id = auth.uid()
  or exists (
    select 1 from public.conversation_members own
    where own.conversation_id = conversation_id and own.user_id = auth.uid()
  )
);

drop policy if exists "members can read messages" on public.messages;
create policy "members can read messages"
on public.messages for select
to authenticated
using (
  exists (
    select 1 from public.conversation_members cm
    where cm.conversation_id = conversation_id and cm.user_id = auth.uid()
  )
);

drop policy if exists "members can send messages" on public.messages;
create policy "members can send messages"
on public.messages for insert
to authenticated
with check (
  sender_id = auth.uid()
  and exists (
    select 1 from public.conversation_members cm
    where cm.conversation_id = conversation_id and cm.user_id = auth.uid()
  )
);

-- Create a direct conversation safely.
create or replace function public.create_direct_conversation(other_user_id uuid)
returns uuid
language plpgsql
security definer set search_path = public
as $$
declare
  existing_id uuid;
  new_id uuid;
begin
  if other_user_id = auth.uid() then
    raise exception 'Cannot create a conversation with yourself';
  end if;

  select cm1.conversation_id into existing_id
  from conversation_members cm1
  join conversation_members cm2
    on cm2.conversation_id = cm1.conversation_id
  join conversations c
    on c.id = cm1.conversation_id
  where cm1.user_id = auth.uid()
    and cm2.user_id = other_user_id
  limit 1;

  if existing_id is not null then
    return existing_id;
  end if;

  insert into conversations default values returning id into new_id;
  insert into conversation_members(conversation_id, user_id)
  values (new_id, auth.uid()), (new_id, other_user_id);

  return new_id;
end;
$$;

create or replace function public.find_direct_conversation(other_user_id uuid)
returns table(conversation_id uuid)
language sql
security definer set search_path = public
as $$
  select cm1.conversation_id
  from conversation_members cm1
  join conversation_members cm2
    on cm2.conversation_id = cm1.conversation_id
  where cm1.user_id = auth.uid()
    and cm2.user_id = other_user_id
  limit 1;
$$;

create or replace function public.my_direct_conversations()
returns table(
  conversation_id uuid,
  user_id uuid,
  username text,
  display_name text,
  avatar_url text
)
language sql
security definer set search_path = public
as $$
  select distinct on (cm.conversation_id)
    cm.conversation_id,
    p.id,
    p.username,
    p.display_name,
    p.avatar_url
  from conversation_members mine
  join conversation_members cm
    on cm.conversation_id = mine.conversation_id
  join profiles p on p.id = cm.user_id
  where mine.user_id = auth.uid()
    and cm.user_id <> auth.uid()
  order by cm.conversation_id;
$$;

grant execute on function public.create_direct_conversation(uuid) to authenticated;
grant execute on function public.find_direct_conversation(uuid) to authenticated;
grant execute on function public.my_direct_conversations() to authenticated;

-- Realtime
alter table public.messages replica identity full;
alter publication supabase_realtime add table public.messages;
